<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4iYq6BL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4iYq6BL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4iYq6BL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4iYq6BL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4iYq6BL\App_KernelDevDebugContainer([
    'container.build_hash' => '4iYq6BL',
    'container.build_id' => '3f571eb6',
    'container.build_time' => 1777683000,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4iYq6BL');
